"""Artifacts section: auto-discovered downloadable output files."""

from __future__ import annotations

import streamlit as st

from dashboard.components import ui
from dashboard.sections.context import DashboardContext
from dashboard.services.artifacts import Artifact, discover_artifacts

_ICON_BY_EXTENSION = {
    "csv": "M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM8 13h2v5H8zM12 13h2v5h-2z",
    "txt": "M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM8 13h8M8 17h5",
}
_DEFAULT_ICON = "M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"


def render(context: DashboardContext) -> None:  # noqa: ARG001 - uniform section signature
    """Render the artifacts section."""
    ui.section_title(
        "Artifacts", "Output Files", "Everything generated by the pipeline, ready to download."
    )

    artifacts = discover_artifacts()
    if not artifacts:
        ui.empty_state(
            "No artifacts found",
            "The outputs directory is empty or unavailable.",
            "📦",
        )
        return

    for start in range(0, len(artifacts), 2):
        row = artifacts[start : start + 2]
        cols = st.columns(len(row), gap="medium")
        for col, artifact in zip(cols, row):
            _render_artifact(col, artifact)


def _render_artifact(column, artifact: Artifact) -> None:
    """Render a single artifact card with a download control."""
    icon = _ICON_BY_EXTENSION.get(artifact.extension, _DEFAULT_ICON)
    meta = f"{artifact.extension.upper()} · {artifact.size_label} · {artifact.modified_label}"
    column.markdown(ui.file_card_html(artifact.name, meta, icon), unsafe_allow_html=True)

    try:
        payload = artifact.path.read_bytes()
    except OSError:
        column.caption("Unavailable for download")
        return

    column.download_button(
        f"Download {artifact.name}",
        data=payload,
        file_name=artifact.name,
        mime=artifact.mime,
        key=f"artifact_{artifact.name}",
        use_container_width=True,
    )
